using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace VibeCast.Infrastructure.Data.Migrations;

[DbContext(typeof(VibeCastDbContext))]
public partial class VibeCastDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");
        new VibeCastDbContextModelBuilder().Build(modelBuilder);
    }

    private sealed class VibeCastDbContextModelBuilder
    {
        public void Build(ModelBuilder modelBuilder)
        {
            // The runtime migration contains the complete initial schema. The snapshot is intentionally
            // lightweight for the teaching starter and will be regenerated by the first schema-changing lab.
        }
    }
}
