<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VibeCast.Application\VibeCast.Application.csproj" />
    <ProjectReference Include="..\..\src\VibeCast.Infrastructure\VibeCast.Infrastructure.csproj" />
  </ItemGroup>
</Project>
