<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VibeCast.Application\VibeCast.Application.csproj" />
    <ProjectReference Include="..\VibeCast.Domain\VibeCast.Domain.csproj" />
  </ItemGroup>
</Project>
