<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>  <UserSecretsId>ea8ceaf4-0ad0-4915-a592-c83437cc597d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />

    <PackageReference Include="Azure.AI.Extensions.OpenAI" />
    <PackageReference Include="Azure.AI.Projects" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VibeCast.Application\VibeCast.Application.csproj" />
    <ProjectReference Include="..\VibeCast.Domain\VibeCast.Domain.csproj" />
  </ItemGroup>
</Project>
